//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export class GitConfigClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "https://localhost:7029";
    }

    get(workId: string): Promise<GitConfigDto> {
        let url_ = this.baseUrl + "/api/GitConfig/Get/{workId}";
        if (workId === undefined || workId === null)
            throw new Error("The parameter 'workId' must be defined.");
        url_ = url_.replace("{workId}", encodeURIComponent("" + workId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGet(_response);
        });
    }

    protected processGet(response: Response): Promise<GitConfigDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if(resultData200['__wrapped'])
            {
                if(resultData200.success){
                    resultData200 = resultData200.result;
                }
                else{
                    throwException(resultData200.error, status, _responseText, _headers)
                }
            }
            result200 = GitConfigDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("服务器发生意外错误。", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GitConfigDto>(null as any);
    }

    save(input: SaveGitConfigInput): Promise<void> {
        let url_ = this.baseUrl + "/api/GitConfig/Save";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(input);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSave(_response);
        });
    }

    protected processSave(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("服务器发生意外错误。", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class GiteeConfigClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "https://localhost:7029";
    }

    get(workId: string): Promise<GiteeWebHookConfigDto> {
        let url_ = this.baseUrl + "/api/GiteeConfig/Get/{workId}";
        if (workId === undefined || workId === null)
            throw new Error("The parameter 'workId' must be defined.");
        url_ = url_.replace("{workId}", encodeURIComponent("" + workId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGet(_response);
        });
    }

    protected processGet(response: Response): Promise<GiteeWebHookConfigDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if(resultData200['__wrapped'])
            {
                if(resultData200.success){
                    resultData200 = resultData200.result;
                }
                else{
                    throwException(resultData200.error, status, _responseText, _headers)
                }
            }
            result200 = GiteeWebHookConfigDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("服务器发生意外错误。", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GiteeWebHookConfigDto>(null as any);
    }

    save(input: SaveGiteeWebHookConfigInput): Promise<void> {
        let url_ = this.baseUrl + "/api/GiteeConfig/Save";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(input);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSave(_response);
        });
    }

    protected processSave(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("服务器发生意外错误。", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    remove(workId: string, configId: number): Promise<void> {
        let url_ = this.baseUrl + "/api/GiteeConfig/Remove/{workId}/{configId}";
        if (workId === undefined || workId === null)
            throw new Error("The parameter 'workId' must be defined.");
        url_ = url_.replace("{workId}", encodeURIComponent("" + workId));
        if (configId === undefined || configId === null)
            throw new Error("The parameter 'configId' must be defined.");
        url_ = url_.replace("{configId}", encodeURIComponent("" + configId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRemove(_response);
        });
    }

    protected processRemove(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("服务器发生意外错误。", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class GroupClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "https://localhost:7029";
    }

    list(): Promise<GroupDto[]> {
        let url_ = this.baseUrl + "/api/Group/List";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processList(_response);
        });
    }

    protected processList(response: Response): Promise<GroupDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if(resultData200['__wrapped'])
            {
                if(resultData200.success){
                    resultData200 = resultData200.result;
                }
                else{
                    throwException(resultData200.error, status, _responseText, _headers)
                }
            }
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(GroupDto.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("服务器发生意外错误。", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GroupDto[]>(null as any);
    }

    query(input: PageGroupInput): Promise<PagingResultOfGroupDto> {
        let url_ = this.baseUrl + "/api/Group/Query";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(input);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processQuery(_response);
        });
    }

    protected processQuery(response: Response): Promise<PagingResultOfGroupDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if(resultData200['__wrapped'])
            {
                if(resultData200.success){
                    resultData200 = resultData200.result;
                }
                else{
                    throwException(resultData200.error, status, _responseText, _headers)
                }
            }
            result200 = PagingResultOfGroupDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("服务器发生意外错误。", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PagingResultOfGroupDto>(null as any);
    }

    save(groupDto: GroupDto): Promise<void> {
        let url_ = this.baseUrl + "/api/Group/Save";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(groupDto);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSave(_response);
        });
    }

    protected processSave(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("服务器发生意外错误。", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    remove(input: RemoveGroupInput): Promise<void> {
        let url_ = this.baseUrl + "/api/Group/Remove";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(input);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRemove(_response);
        });
    }

    protected processRemove(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("服务器发生意外错误。", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class SettingClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "https://localhost:7029";
    }

    getBasicSetting(): Promise<BasicSetting> {
        let url_ = this.baseUrl + "/api/Setting/GetBasicSetting";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetBasicSetting(_response);
        });
    }

    protected processGetBasicSetting(response: Response): Promise<BasicSetting> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if(resultData200['__wrapped'])
            {
                if(resultData200.success){
                    resultData200 = resultData200.result;
                }
                else{
                    throwException(resultData200.error, status, _responseText, _headers)
                }
            }
            result200 = BasicSetting.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("服务器发生意外错误。", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BasicSetting>(null as any);
    }

    saveBasicSetting(basicSetting: BasicSetting): Promise<void> {
        let url_ = this.baseUrl + "/api/Setting/SaveBasicSetting";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(basicSetting);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSaveBasicSetting(_response);
        });
    }

    protected processSaveBasicSetting(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("服务器发生意外错误。", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class WorkClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "https://localhost:7029";
    }

    query(input: PagingInput): Promise<PagingResultOfWorkDto> {
        let url_ = this.baseUrl + "/api/Work/Query";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(input);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processQuery(_response);
        });
    }

    protected processQuery(response: Response): Promise<PagingResultOfWorkDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if(resultData200['__wrapped'])
            {
                if(resultData200.success){
                    resultData200 = resultData200.result;
                }
                else{
                    throwException(resultData200.error, status, _responseText, _headers)
                }
            }
            result200 = PagingResultOfWorkDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("服务器发生意外错误。", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PagingResultOfWorkDto>(null as any);
    }

    save(workDto: WorkDto): Promise<void> {
        let url_ = this.baseUrl + "/api/Work/Save";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(workDto);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSave(_response);
        });
    }

    protected processSave(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("服务器发生意外错误。", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    remove(input: RemoveWorkInput): Promise<void> {
        let url_ = this.baseUrl + "/api/Work/Remove";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(input);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRemove(_response);
        });
    }

    protected processRemove(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("服务器发生意外错误。", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    detail(workId: string): Promise<WorkDetailDto> {
        let url_ = this.baseUrl + "/api/Work/Detail/{workId}";
        if (workId === undefined || workId === null)
            throw new Error("The parameter 'workId' must be defined.");
        url_ = url_.replace("{workId}", encodeURIComponent("" + workId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDetail(_response);
        });
    }

    protected processDetail(response: Response): Promise<WorkDetailDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if(resultData200['__wrapped'])
            {
                if(resultData200.success){
                    resultData200 = resultData200.result;
                }
                else{
                    throwException(resultData200.error, status, _responseText, _headers)
                }
            }
            result200 = WorkDetailDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("服务器发生意外错误。", status, _responseText, _headers);
            });
        }
        return Promise.resolve<WorkDetailDto>(null as any);
    }

    saveDetail(detail: WorkDetailDto): Promise<void> {
        let url_ = this.baseUrl + "/api/Work/SaveDetail";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(detail);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSaveDetail(_response);
        });
    }

    protected processSaveDetail(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("服务器发生意外错误。", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    saveScripts(dto: BuildScriptDto): Promise<void> {
        let url_ = this.baseUrl + "/api/Work/SaveScripts";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSaveScripts(_response);
        });
    }

    protected processSaveScripts(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("服务器发生意外错误。", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class WorkExecutionLogClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "https://localhost:7029";
    }

    getSummaries(workId: string): Promise<WorkExecutionLogSummary[]> {
        let url_ = this.baseUrl + "/api/WorkExecutionLog/GetSummaries/{workId}";
        if (workId === undefined || workId === null)
            throw new Error("The parameter 'workId' must be defined.");
        url_ = url_.replace("{workId}", encodeURIComponent("" + workId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetSummaries(_response);
        });
    }

    protected processGetSummaries(response: Response): Promise<WorkExecutionLogSummary[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if(resultData200['__wrapped'])
            {
                if(resultData200.success){
                    resultData200 = resultData200.result;
                }
                else{
                    throwException(resultData200.error, status, _responseText, _headers)
                }
            }
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(WorkExecutionLogSummary.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("服务器发生意外错误。", status, _responseText, _headers);
            });
        }
        return Promise.resolve<WorkExecutionLogSummary[]>(null as any);
    }

    getDetail(workId: string, logId: number): Promise<WorkExecutionLog> {
        let url_ = this.baseUrl + "/api/WorkExecutionLog/GetDetail/{workId}/{logId}";
        if (workId === undefined || workId === null)
            throw new Error("The parameter 'workId' must be defined.");
        url_ = url_.replace("{workId}", encodeURIComponent("" + workId));
        if (logId === undefined || logId === null)
            throw new Error("The parameter 'logId' must be defined.");
        url_ = url_.replace("{logId}", encodeURIComponent("" + logId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetDetail(_response);
        });
    }

    protected processGetDetail(response: Response): Promise<WorkExecutionLog> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if(resultData200['__wrapped'])
            {
                if(resultData200.success){
                    resultData200 = resultData200.result;
                }
                else{
                    throwException(resultData200.error, status, _responseText, _headers)
                }
            }
            result200 = WorkExecutionLog.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("服务器发生意外错误。", status, _responseText, _headers);
            });
        }
        return Promise.resolve<WorkExecutionLog>(null as any);
    }
}

export class WorkRunnerClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "https://localhost:7029";
    }

    run(workId: string): Promise<void> {
        let url_ = this.baseUrl + "/api/WorkRunner/Run/{workId}";
        if (workId === undefined || workId === null)
            throw new Error("The parameter 'workId' must be defined.");
        url_ = url_.replace("{workId}", encodeURIComponent("" + workId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRun(_response);
        });
    }

    protected processRun(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("服务器发生意外错误。", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class DtoOfInteger implements IDtoOfInteger {
    id!: number;

    constructor(data?: IDtoOfInteger) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
        }
    }

    static fromJS(data: any): DtoOfInteger {
        data = typeof data === 'object' ? data : {};
        let result = new DtoOfInteger();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        return data;
    }
}

export interface IDtoOfInteger {
    id: number;
}

export class GitConfigDto extends DtoOfInteger implements IGitConfigDto {
    workId!: string;
    addressType?: string | undefined;
    repositoryAddress?: string | undefined;
    branch?: string | undefined;
    tag?: string | undefined;

    constructor(data?: IGitConfigDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.workId = _data["workId"];
            this.addressType = _data["addressType"];
            this.repositoryAddress = _data["repositoryAddress"];
            this.branch = _data["branch"];
            this.tag = _data["tag"];
        }
    }

    static fromJS(data: any): GitConfigDto {
        data = typeof data === 'object' ? data : {};
        let result = new GitConfigDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["workId"] = this.workId;
        data["addressType"] = this.addressType;
        data["repositoryAddress"] = this.repositoryAddress;
        data["branch"] = this.branch;
        data["tag"] = this.tag;
        super.toJSON(data);
        return data;
    }
}

export interface IGitConfigDto extends IDtoOfInteger {
    workId: string;
    addressType?: string | undefined;
    repositoryAddress?: string | undefined;
    branch?: string | undefined;
    tag?: string | undefined;
}

export class SaveGitConfigInput implements ISaveGitConfigInput {
    toSave?: GitConfigDto | undefined;

    constructor(data?: ISaveGitConfigInput) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.toSave = _data["toSave"] ? GitConfigDto.fromJS(_data["toSave"]) : <any>undefined;
        }
    }

    static fromJS(data: any): SaveGitConfigInput {
        data = typeof data === 'object' ? data : {};
        let result = new SaveGitConfigInput();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["toSave"] = this.toSave ? this.toSave.toJSON() : <any>undefined;
        return data;
    }
}

export interface ISaveGitConfigInput {
    toSave?: GitConfigDto | undefined;
}

export class GiteeWebHookConfigDto extends DtoOfInteger implements IGiteeWebHookConfigDto {
    workId!: string;
    webHookUrl!: string;
    authentication!: GiteeWebHookAuthentication;
    authenticationKey!: GiteeAuthenticationKey;
    events!: string[];

    constructor(data?: IGiteeWebHookConfigDto) {
        super(data);
        if (!data) {
            this.authenticationKey = new GiteeAuthenticationKey();
            this.events = [];
        }
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.workId = _data["workId"];
            this.webHookUrl = _data["webHookUrl"];
            this.authentication = _data["authentication"];
            this.authenticationKey = _data["authenticationKey"] ? GiteeAuthenticationKey.fromJS(_data["authenticationKey"]) : new GiteeAuthenticationKey();
            if (Array.isArray(_data["events"])) {
                this.events = [] as any;
                for (let item of _data["events"])
                    this.events!.push(item);
            }
        }
    }

    static fromJS(data: any): GiteeWebHookConfigDto {
        data = typeof data === 'object' ? data : {};
        let result = new GiteeWebHookConfigDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["workId"] = this.workId;
        data["webHookUrl"] = this.webHookUrl;
        data["authentication"] = this.authentication;
        data["authenticationKey"] = this.authenticationKey ? this.authenticationKey.toJSON() : <any>undefined;
        if (Array.isArray(this.events)) {
            data["events"] = [];
            for (let item of this.events)
                data["events"].push(item);
        }
        super.toJSON(data);
        return data;
    }
}

export interface IGiteeWebHookConfigDto extends IDtoOfInteger {
    workId: string;
    webHookUrl: string;
    authentication: GiteeWebHookAuthentication;
    authenticationKey: GiteeAuthenticationKey;
    events: string[];
}

export enum GiteeWebHookAuthentication {
    Srcret = 1,
    SignatureKey = 2,
}

export class GiteeAuthenticationKey implements IGiteeAuthenticationKey {
    value?: string | undefined;

    constructor(data?: IGiteeAuthenticationKey) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.value = _data["value"];
        }
    }

    static fromJS(data: any): GiteeAuthenticationKey {
        data = typeof data === 'object' ? data : {};
        let result = new GiteeAuthenticationKey();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["value"] = this.value;
        return data;
    }
}

export interface IGiteeAuthenticationKey {
    value?: string | undefined;
}

export class SaveGiteeWebHookConfigInput extends DtoOfInteger implements ISaveGiteeWebHookConfigInput {
    workId!: string;
    webHookUrl!: string;
    authentication!: GiteeWebHookAuthentication;
    authenticationKey!: GiteeAuthenticationKey;
    events!: string[];

    constructor(data?: ISaveGiteeWebHookConfigInput) {
        super(data);
        if (!data) {
            this.authenticationKey = new GiteeAuthenticationKey();
            this.events = [];
        }
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.workId = _data["workId"];
            this.webHookUrl = _data["webHookUrl"];
            this.authentication = _data["authentication"];
            this.authenticationKey = _data["authenticationKey"] ? GiteeAuthenticationKey.fromJS(_data["authenticationKey"]) : new GiteeAuthenticationKey();
            if (Array.isArray(_data["events"])) {
                this.events = [] as any;
                for (let item of _data["events"])
                    this.events!.push(item);
            }
        }
    }

    static fromJS(data: any): SaveGiteeWebHookConfigInput {
        data = typeof data === 'object' ? data : {};
        let result = new SaveGiteeWebHookConfigInput();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["workId"] = this.workId;
        data["webHookUrl"] = this.webHookUrl;
        data["authentication"] = this.authentication;
        data["authenticationKey"] = this.authenticationKey ? this.authenticationKey.toJSON() : <any>undefined;
        if (Array.isArray(this.events)) {
            data["events"] = [];
            for (let item of this.events)
                data["events"].push(item);
        }
        super.toJSON(data);
        return data;
    }
}

export interface ISaveGiteeWebHookConfigInput extends IDtoOfInteger {
    workId: string;
    webHookUrl: string;
    authentication: GiteeWebHookAuthentication;
    authenticationKey: GiteeAuthenticationKey;
    events: string[];
}

export class DtoOfGuid implements IDtoOfGuid {
    id!: string;

    constructor(data?: IDtoOfGuid) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
        }
    }

    static fromJS(data: any): DtoOfGuid {
        data = typeof data === 'object' ? data : {};
        let result = new DtoOfGuid();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        return data;
    }
}

export interface IDtoOfGuid {
    id: string;
}

export class GroupDto extends DtoOfGuid implements IGroupDto {
    name?: string | undefined;
    description?: string | undefined;

    constructor(data?: IGroupDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.name = _data["name"];
            this.description = _data["description"];
        }
    }

    static fromJS(data: any): GroupDto {
        data = typeof data === 'object' ? data : {};
        let result = new GroupDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["description"] = this.description;
        super.toJSON(data);
        return data;
    }
}

export interface IGroupDto extends IDtoOfGuid {
    name?: string | undefined;
    description?: string | undefined;
}

export class PagingResultOfGroupDto implements IPagingResultOfGroupDto {
    rows!: GroupDto[];
    total!: number;
    page!: number;
    pageSize!: number;

    constructor(data?: IPagingResultOfGroupDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.rows = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["rows"])) {
                this.rows = [] as any;
                for (let item of _data["rows"])
                    this.rows!.push(GroupDto.fromJS(item));
            }
            this.total = _data["total"];
            this.page = _data["page"];
            this.pageSize = _data["pageSize"];
        }
    }

    static fromJS(data: any): PagingResultOfGroupDto {
        data = typeof data === 'object' ? data : {};
        let result = new PagingResultOfGroupDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.rows)) {
            data["rows"] = [];
            for (let item of this.rows)
                data["rows"].push(item.toJSON());
        }
        data["total"] = this.total;
        data["page"] = this.page;
        data["pageSize"] = this.pageSize;
        return data;
    }
}

export interface IPagingResultOfGroupDto {
    rows: GroupDto[];
    total: number;
    page: number;
    pageSize: number;
}

export class PageGroupInput implements IPageGroupInput {
    page!: number;
    pageSize!: number;

    constructor(data?: IPageGroupInput) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.page = _data["page"];
            this.pageSize = _data["pageSize"];
        }
    }

    static fromJS(data: any): PageGroupInput {
        data = typeof data === 'object' ? data : {};
        let result = new PageGroupInput();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["page"] = this.page;
        data["pageSize"] = this.pageSize;
        return data;
    }
}

export interface IPageGroupInput {
    page: number;
    pageSize: number;
}

export class RemoveGroupInput implements IRemoveGroupInput {
    id!: string;

    constructor(data?: IRemoveGroupInput) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
        }
    }

    static fromJS(data: any): RemoveGroupInput {
        data = typeof data === 'object' ? data : {};
        let result = new RemoveGroupInput();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        return data;
    }
}

export interface IRemoveGroupInput {
    id: string;
}

export class BasicSetting implements IBasicSetting {
    baseWorkDirectory?: string | undefined;

    constructor(data?: IBasicSetting) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.baseWorkDirectory = _data["baseWorkDirectory"];
        }
    }

    static fromJS(data: any): BasicSetting {
        data = typeof data === 'object' ? data : {};
        let result = new BasicSetting();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["baseWorkDirectory"] = this.baseWorkDirectory;
        return data;
    }
}

export interface IBasicSetting {
    baseWorkDirectory?: string | undefined;
}

export class PagingResultOfWorkDto implements IPagingResultOfWorkDto {
    rows!: WorkDto[];
    total!: number;
    page!: number;
    pageSize!: number;

    constructor(data?: IPagingResultOfWorkDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.rows = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["rows"])) {
                this.rows = [] as any;
                for (let item of _data["rows"])
                    this.rows!.push(WorkDto.fromJS(item));
            }
            this.total = _data["total"];
            this.page = _data["page"];
            this.pageSize = _data["pageSize"];
        }
    }

    static fromJS(data: any): PagingResultOfWorkDto {
        data = typeof data === 'object' ? data : {};
        let result = new PagingResultOfWorkDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.rows)) {
            data["rows"] = [];
            for (let item of this.rows)
                data["rows"].push(item.toJSON());
        }
        data["total"] = this.total;
        data["page"] = this.page;
        data["pageSize"] = this.pageSize;
        return data;
    }
}

export interface IPagingResultOfWorkDto {
    rows: WorkDto[];
    total: number;
    page: number;
    pageSize: number;
}

export class WorkDto extends DtoOfGuid implements IWorkDto {
    displayName!: string;
    externalConfigType!: string;

    constructor(data?: IWorkDto) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.displayName = _data["displayName"];
            this.externalConfigType = _data["externalConfigType"];
        }
    }

    static fromJS(data: any): WorkDto {
        data = typeof data === 'object' ? data : {};
        let result = new WorkDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["displayName"] = this.displayName;
        data["externalConfigType"] = this.externalConfigType;
        super.toJSON(data);
        return data;
    }
}

export interface IWorkDto extends IDtoOfGuid {
    displayName: string;
    externalConfigType: string;
}

export class PagingInput implements IPagingInput {
    page!: number;
    pageSize!: number;

    constructor(data?: IPagingInput) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.page = _data["page"];
            this.pageSize = _data["pageSize"];
        }
    }

    static fromJS(data: any): PagingInput {
        data = typeof data === 'object' ? data : {};
        let result = new PagingInput();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["page"] = this.page;
        data["pageSize"] = this.pageSize;
        return data;
    }
}

export interface IPagingInput {
    page: number;
    pageSize: number;
}

export class RemoveWorkInput implements IRemoveWorkInput {
    workId!: string;

    constructor(data?: IRemoveWorkInput) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.workId = _data["workId"];
        }
    }

    static fromJS(data: any): RemoveWorkInput {
        data = typeof data === 'object' ? data : {};
        let result = new RemoveWorkInput();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["workId"] = this.workId;
        return data;
    }
}

export interface IRemoveWorkInput {
    workId: string;
}

export class WorkDetailDto implements IWorkDetailDto {
    work?: WorkDto | undefined;
    script?: BuildScript | undefined;
    config?: GiteeWebHookConfigDto | undefined;

    constructor(data?: IWorkDetailDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.work = _data["work"] ? WorkDto.fromJS(_data["work"]) : <any>undefined;
            this.script = _data["script"] ? BuildScript.fromJS(_data["script"]) : <any>undefined;
            this.config = _data["config"] ? GiteeWebHookConfigDto.fromJS(_data["config"]) : <any>undefined;
        }
    }

    static fromJS(data: any): WorkDetailDto {
        data = typeof data === 'object' ? data : {};
        let result = new WorkDetailDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["work"] = this.work ? this.work.toJSON() : <any>undefined;
        data["script"] = this.script ? this.script.toJSON() : <any>undefined;
        data["config"] = this.config ? this.config.toJSON() : <any>undefined;
        return data;
    }
}

export interface IWorkDetailDto {
    work?: WorkDto | undefined;
    script?: BuildScript | undefined;
    config?: GiteeWebHookConfigDto | undefined;
}

export class EntityOfInteger implements IEntityOfInteger {
    id!: number;
    createdAt?: Date | undefined;
    modifedAt?: Date | undefined;

    constructor(data?: IEntityOfInteger) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : <any>undefined;
            this.modifedAt = _data["modifedAt"] ? new Date(_data["modifedAt"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): EntityOfInteger {
        data = typeof data === 'object' ? data : {};
        let result = new EntityOfInteger();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : <any>undefined;
        data["modifedAt"] = this.modifedAt ? this.modifedAt.toISOString() : <any>undefined;
        return data;
    }
}

export interface IEntityOfInteger {
    id: number;
    createdAt?: Date | undefined;
    modifedAt?: Date | undefined;
}

export class BuildScript extends EntityOfInteger implements IBuildScript {
    workId!: string;
    sortNumber!: number;
    script!: string[];

    constructor(data?: IBuildScript) {
        super(data);
        if (!data) {
            this.script = [];
        }
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.workId = _data["workId"];
            this.sortNumber = _data["sortNumber"];
            if (Array.isArray(_data["script"])) {
                this.script = [] as any;
                for (let item of _data["script"])
                    this.script!.push(item);
            }
        }
    }

    static fromJS(data: any): BuildScript {
        data = typeof data === 'object' ? data : {};
        let result = new BuildScript();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["workId"] = this.workId;
        data["sortNumber"] = this.sortNumber;
        if (Array.isArray(this.script)) {
            data["script"] = [];
            for (let item of this.script)
                data["script"].push(item);
        }
        super.toJSON(data);
        return data;
    }
}

export interface IBuildScript extends IEntityOfInteger {
    workId: string;
    sortNumber: number;
    script: string[];
}

export class BuildScriptDto extends DtoOfInteger implements IBuildScriptDto {
    workId!: string;
    sortNumber!: number;
    script!: string[];

    constructor(data?: IBuildScriptDto) {
        super(data);
        if (!data) {
            this.script = [];
        }
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.workId = _data["workId"];
            this.sortNumber = _data["sortNumber"];
            if (Array.isArray(_data["script"])) {
                this.script = [] as any;
                for (let item of _data["script"])
                    this.script!.push(item);
            }
        }
    }

    static fromJS(data: any): BuildScriptDto {
        data = typeof data === 'object' ? data : {};
        let result = new BuildScriptDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["workId"] = this.workId;
        data["sortNumber"] = this.sortNumber;
        if (Array.isArray(this.script)) {
            data["script"] = [];
            for (let item of this.script)
                data["script"].push(item);
        }
        super.toJSON(data);
        return data;
    }
}

export interface IBuildScriptDto extends IDtoOfInteger {
    workId: string;
    sortNumber: number;
    script: string[];
}

export class DtoOfLong implements IDtoOfLong {
    id!: number;

    constructor(data?: IDtoOfLong) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
        }
    }

    static fromJS(data: any): DtoOfLong {
        data = typeof data === 'object' ? data : {};
        let result = new DtoOfLong();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        return data;
    }
}

export interface IDtoOfLong {
    id: number;
}

export class WorkExecutionLogSummary extends DtoOfLong implements IWorkExecutionLogSummary {
    workId!: string;
    executeStartAt?: Date | undefined;
    executeEndAt?: Date | undefined;
    elapsedTime?: string | undefined;
    status!: WebExecutionStatus;
    success?: boolean | undefined;

    constructor(data?: IWorkExecutionLogSummary) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.workId = _data["workId"];
            this.executeStartAt = _data["executeStartAt"] ? new Date(_data["executeStartAt"].toString()) : <any>undefined;
            this.executeEndAt = _data["executeEndAt"] ? new Date(_data["executeEndAt"].toString()) : <any>undefined;
            this.elapsedTime = _data["elapsedTime"];
            this.status = _data["status"];
            this.success = _data["success"];
        }
    }

    static fromJS(data: any): WorkExecutionLogSummary {
        data = typeof data === 'object' ? data : {};
        let result = new WorkExecutionLogSummary();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["workId"] = this.workId;
        data["executeStartAt"] = this.executeStartAt ? this.executeStartAt.toISOString() : <any>undefined;
        data["executeEndAt"] = this.executeEndAt ? this.executeEndAt.toISOString() : <any>undefined;
        data["elapsedTime"] = this.elapsedTime;
        data["status"] = this.status;
        data["success"] = this.success;
        super.toJSON(data);
        return data;
    }
}

export interface IWorkExecutionLogSummary extends IDtoOfLong {
    workId: string;
    executeStartAt?: Date | undefined;
    executeEndAt?: Date | undefined;
    elapsedTime?: string | undefined;
    status: WebExecutionStatus;
    success?: boolean | undefined;
}

export enum WebExecutionStatus {
    Ready = 1,
    Executing = 2,
    Completed = 3,
}

export class EntityOfLong implements IEntityOfLong {
    id!: number;
    createdAt?: Date | undefined;
    modifedAt?: Date | undefined;

    constructor(data?: IEntityOfLong) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : <any>undefined;
            this.modifedAt = _data["modifedAt"] ? new Date(_data["modifedAt"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): EntityOfLong {
        data = typeof data === 'object' ? data : {};
        let result = new EntityOfLong();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : <any>undefined;
        data["modifedAt"] = this.modifedAt ? this.modifedAt.toISOString() : <any>undefined;
        return data;
    }
}

export interface IEntityOfLong {
    id: number;
    createdAt?: Date | undefined;
    modifedAt?: Date | undefined;
}

export class WorkExecutionLog extends EntityOfLong implements IWorkExecutionLog {
    workId!: string;
    executeStartAt?: Date | undefined;
    executeEndAt?: Date | undefined;
    elapsedTime?: string | undefined;
    status!: WebExecutionStatus;
    success?: boolean | undefined;
    exception?: string | undefined;
    script?: string[] | undefined;
    results?: ShellExecutedResultLine[] | undefined;

    constructor(data?: IWorkExecutionLog) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.workId = _data["workId"];
            this.executeStartAt = _data["executeStartAt"] ? new Date(_data["executeStartAt"].toString()) : <any>undefined;
            this.executeEndAt = _data["executeEndAt"] ? new Date(_data["executeEndAt"].toString()) : <any>undefined;
            this.elapsedTime = _data["elapsedTime"];
            this.status = _data["status"];
            this.success = _data["success"];
            this.exception = _data["exception"];
            if (Array.isArray(_data["script"])) {
                this.script = [] as any;
                for (let item of _data["script"])
                    this.script!.push(item);
            }
            if (Array.isArray(_data["results"])) {
                this.results = [] as any;
                for (let item of _data["results"])
                    this.results!.push(ShellExecutedResultLine.fromJS(item));
            }
        }
    }

    static fromJS(data: any): WorkExecutionLog {
        data = typeof data === 'object' ? data : {};
        let result = new WorkExecutionLog();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["workId"] = this.workId;
        data["executeStartAt"] = this.executeStartAt ? this.executeStartAt.toISOString() : <any>undefined;
        data["executeEndAt"] = this.executeEndAt ? this.executeEndAt.toISOString() : <any>undefined;
        data["elapsedTime"] = this.elapsedTime;
        data["status"] = this.status;
        data["success"] = this.success;
        data["exception"] = this.exception;
        if (Array.isArray(this.script)) {
            data["script"] = [];
            for (let item of this.script)
                data["script"].push(item);
        }
        if (Array.isArray(this.results)) {
            data["results"] = [];
            for (let item of this.results)
                data["results"].push(item.toJSON());
        }
        super.toJSON(data);
        return data;
    }
}

export interface IWorkExecutionLog extends IEntityOfLong {
    workId: string;
    executeStartAt?: Date | undefined;
    executeEndAt?: Date | undefined;
    elapsedTime?: string | undefined;
    status: WebExecutionStatus;
    success?: boolean | undefined;
    exception?: string | undefined;
    script?: string[] | undefined;
    results?: ShellExecutedResultLine[] | undefined;
}

export class ShellExecutedResultLine implements IShellExecutedResultLine {
    level!: ResultLineLevel;
    message!: string;
    stackTrace?: string | undefined;
    exception?: string | undefined;

    constructor(data?: IShellExecutedResultLine) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.level = _data["level"];
            this.message = _data["message"];
            this.stackTrace = _data["stackTrace"];
            this.exception = _data["exception"];
        }
    }

    static fromJS(data: any): ShellExecutedResultLine {
        data = typeof data === 'object' ? data : {};
        let result = new ShellExecutedResultLine();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["level"] = this.level;
        data["message"] = this.message;
        data["stackTrace"] = this.stackTrace;
        data["exception"] = this.exception;
        return data;
    }
}

export interface IShellExecutedResultLine {
    level: ResultLineLevel;
    message: string;
    stackTrace?: string | undefined;
    exception?: string | undefined;
}

export enum ResultLineLevel {
    Debug = 1,
    Info = 2,
    Warning = 3,
    Error = 4,
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}